name: lepsi_sunmi_cloud_printer
description: "Fork of lepsi_sunmi_cloud_printer, providing better support for Sunmi Cloud Printers."
version: 0.0.5
repository: "https://github.com/techheavencz/lepsi_sunmi_cloud_printer"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.lepsi_sunmi_cloud_printer
        pluginClass: SunmiCloudPrinterPlugin