name: sunmi_cloud_printer
description: "Sunmi support package that allows you to easily interface with your cloud printer"
version: 0.0.5
repository: "https://github.com/FrenkyDema/sunmi_cloud_printer"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sunmi_cloud_printer
        pluginClass: SunmiCloudPrinterPlugin